### ISSUE TITLE
Deflicker

### ISSUE THREAD

**Issue by makseq** [isl-org/DPT#45]
Thank you for such great software! 
Do you have ideas on how to reduce the flickering effect between frames from the same video?

**Comment by AlexeyAB** [comment]
1. Try to use model with absolute depth so it will not recalculate dynamic range for each frame:
    `python run_monodepth.py --model_type dpt_hybrid_nyu --absolute_depth`

2. Additionally, you can average the output between 3 frames

3. Finally the model should be re-trained on Video with spatio-temporal patches instead of spatial patches or/and it should use RNN/GRU/LSTM-layers

**Comment by makseq** [comment]
Aren't you afraid that the result of step (2) will be blurry?

**Comment by AlexeyAB** [comment]
Yes, the 2nd will result in blur on fast motion. Therefore, it is best used for video - the 3rd: spatio-temporal patches, RNN / GRU / LSTM, ... or combine Mono-depth with SLAM

**Comment by makseq** [comment]
Do you know about approaches like this: https://github.com/princeton-vl/DeepV2D/ ? Does it produce more stable results?

**Comment by jiaqixuac** [comment]
Hi @makseq , sorry to bother you. Did you find the solution for this?
I want to infer depth for some random videos (wide data distribution, seems opt for DPT), and I also get flicker issues.

**Comment by makseq** [comment]
@jiaqixuac no :( looks like a difficult task..
